version: "3.3"

services:
  keycloak:
    image: "${BASE_REPO}/keycloak:${KEYCLOAK_VERSION}"
    user: root
    environment:
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_HOST}:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYClOAK_DB_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      #KC_LOG_LEVEL: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      JGROUPS_DISCOVERY_EXTERNAL_IP: ${KEYCLOAK_ISPN_EXTERNAL_IP}
      GA_ENABLE: ${GA_ENABLE}
      GA_API_KEY: ${GA_API_KEY}
      GA_AUTH_DOMAIN: ${GA_AUTH_DOMAIN}
      GA_PROJECT_ID: ${GA_PROJECT_ID}
      GA_STORAGE_BUCKET: ${GA_STORAGE_BUCKET}
      GA_MESSAGING_SENDER_ID: ${GA_MESSAGING_SENDER_ID}
      GA_APP_ID: ${GA_APP_ID}
      GA_MEASUREMENT_ID: ${GA_MEASUREMENT_ID}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_EVENTS: ${KAFKA_EVENTS}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: ${QUARKUS_HTTP_ACCESS_LOG_ENABLED}
      QUARKUS_HTTP_RECORD_REQUEST_START_TIME: ${QUARKUS_HTTP_RECORD_REQUEST_START_TIME}
      QUARKUS_HTTP_ACCESS_LOG_EXCLUDE_PATTERN: ${QUARKUS_HTTP_ACCESS_LOG_EXCLUDE_PATTERN}
      QUARKUS_HTTP_ACCESS_LOG_PATTERN: ${QUARKUS_HTTP_ACCESS_LOG_PATTERN}
    ports:
      - "${KEYCLOAK_PORT}:8080"
      - "7800:7800"
    command:
      - start
      - --optimized
      - --proxy=edge
      - --hostname-strict-https=false
    restart: always
