version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres:13.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-"19.0"}
    volumes:
      - ../keycloak/themes:/opt/keycloak/themes
      # Comment this line to disable custom providers
      - ../keycloak/services/target/viettelcloud-services-0.2.0-SNAPSHOT.jar:/opt/keycloak/providers/viettelcloud-services-0.2.0-SNAPSHOT.jar
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_LOG_LEVEL: INFO
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      GA_ENABLE: disable
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: ${QUARKUS_HTTP_ACCESS_LOG_ENABLED}
      QUARKUS_HTTP_RECORD_REQUEST_START_TIME: ${QUARKUS_HTTP_RECORD_REQUEST_START_TIME}
      QUARKUS_HTTP_ACCESS_LOG_EXCLUDE_PATTERN: ${QUARKUS_HTTP_ACCESS_LOG_EXCLUDE_PATTERN}
      QUARKUS_HTTP_ACCESS_LOG_PATTERN: ${QUARKUS_HTTP_ACCESS_LOG_PATTERN}
    command:
      - start
      - --proxy=edge
      - --hostname-strict-https=false
      - --hostname=$KC_HOSTNAME
      # Enable theme caching for dynamic reloading in dev environment
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      # Comment to disable locale selector provider
      - --spi-locale-selector-provider=custom
    depends_on:
      - postgres
    extra_hosts:
       - "smtp.viettel.com.vn:125.235.240.36"

  nginx:
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/server-ssl.conf:/etc/nginx/conf.d/server.conf:ro
      - ./nginx/certs/:/etc/nginx/certs/:ro
